[project]
name = "maxim-observability-openai"
version = "0.1.0"
requires-python = ">=3.9"
description = "Maxim AI cookbook for gemini."
authors = [{ name = "Maxim Engineering", email = "eng@getmaxim.ai" }]
dependencies = [
    "openai>=1.65.4",
    "python-dotenv>=1.0.1",
]
