[project]
name = "maxim-gemini-cookbook"
version = "0.1.0"
requires-python = ">=3.9"
description = "Maxim AI cookbook for gemini."
authors = [{ name = "Maxim Engineering", email = "eng@getmaxim.ai" }]
dependencies = [
    "flask>=3.1.0",
    "google-genai>=1.0.0",
    "python-dotenv>=1.0.1",
]
