[project]
name = "manual-tracing"
version = "0.1.0"
description = "Using manual tracing approach to trace agents on Maxim"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "maxim-py>=3.6.2",
    "openai>=1.78.1",
    "python-dotenv>=1.1.0",
]
