[project]
name = "maxim-attachments"
version = "0.1.0"
description = "Attachments in Maxim logs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "python-dotenv>=1.1.0",
]
